apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: default
  labels:
    app: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: fcg-notifications-api:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: notifications-api-config
            - secretRef:
                name: notifications-api-secret
