apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  namespace: fcg-fase3
spec:
  replicas: 1
  selector:
    matchLabels: { app: kong-database }
  template:
    metadata:
      labels: { app: kong-database }
    spec:
      containers:
        - name: kong-database
          image: postgres:15-alpine
          ports: [{ containerPort: 5432 }]
          env:
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "kong"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: kong-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: kong-db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kong-database
  namespace: fcg-fase3
spec:
  selector: { app: kong-database }
  ports:
    - port: 5432
      targetPort: 5432
